### ISSUE TITLE
Relicense under GNU GPLv3+

### ISSUE THREAD

**Issue by McSinyx** [Bitl/Black-Shades-Enhanced#12]
Since [David Rosen has relicensed Black Shades under the GNU General Public License version 3 or later](https://lists.sr.ht/~cnx/blackshades/%3CCC5KX31G7Y9G.FUEV6FB9UG99%40nix%3E), you might want to update the copying information on this repository as well.  IANAL but I think it was not entirely legal to make derivation from the copy under uDevGame license.

**Comment by Bitl** [comment]
Now it's under the GNU GPLv3 license.

**Comment by Bitl** [comment]
#13 added
