### ISSUE TITLE
Sniper zooming out on idle

### ISSUE THREAD

**Issue by z33ky** [Bitl/Black-Shades-Enhanced#7]
I have a weird issue that when just crouching down with the sniperrifle and not pressing any keys or moving the mouse, the zoom will disengage after a second or two.
It seems SDL is erroneously generating a KEYUP-event for LCTRL for whatever reason. I have a workaround:
```
diff --git a/blackshades/Source/GameLoop.cpp b/blackshades/Source/GameLoop.cpp
index d2bc745..97dbd8b 100644
--- a/blackshades/Source/GameLoop.cpp
+++ b/blackshades/Source/GameLoop.cpp
@@ -318,6 +318,8 @@ static void DoSDLKey(Game *g, SDL_Event *event)
    }

    mackey = sdlkeymap[event->key.keysym.sym];
+   if(mackey == MAC_CONTROL_KEY)
+       press = SDL_GetModState() & (KMOD_LCTRL | KMOD_RCTRL);

    if (mackey != -1) {
        index = mackey / 8;
```
`SDL_GetModState()` seems to return the state correctly. I didn't create a PR since I fear it might just be my system that is behaving weird. So, do you get this, too?

**Comment by Bitl** [comment]
will add this in 1.1.2
