### ISSUE TITLE
Permanent slomo

### ISSUE THREAD

**Issue by norogoth** [Bitl/Black-Shades-Enhanced#8]
I played this game when it first came out and I remember there being a permanent slomo mode you could activate. I originally may have been playing on a Mac OS 9 though. Do you know about this feature?

Great work on this project. I know a little C++ and I would love to figure out how to get into modding some day.

**Comment by norogoth** [comment]
It seems that I cannot run the program or select a file to run. (I have never done this kind of thing before).

![can't select](https://user-images.githubusercontent.com/52639031/81481416-f0fe7380-91e4-11ea-8d24-941e09e8f409.PNG)
![Star_grayed](https://user-images.githubusercontent.com/52639031/81481417-f1970a00-91e4-11ea-8d1c-a858a2468a00.PNG)

**Comment by norogoth** [comment]
The start button and is grayed out and I cannot seem to select a startup item.

**Comment by Bitl** [comment]
Hi, I apologize for the long delay

i'll see what I can to to implement a permanent slo mo mode.

Also, the game is now compilable under VS 2019, so there shouldn't be any issues getting it to compile and run :D

EDIT: permanent slow motion is enabled through the debug/fps meter options, which can be set inn the config.txt file!

**Comment by norogoth** [comment]
Sounds great. Thanks. Is that a recent fix or should it have compiled
before as well?
